using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ThirdPersonCam : MonoBehaviour
{
    [Header("References")]
    public Transform orientation;
    public Transform player;
    public Transform playerObj;
    public Rigidbody rb;

    public float rotationSpeed;

    public Transform combatLookAt;

    public GameObject thirdPersonCam;
    public GameObject combatCam;

    public CameraStyle currentStyle;
    public GameStatus gameStatus;
    public enum CameraStyle
    {
        Basic,
        Shoot
    }

    private void Start()
    {
        Cursor.lockState = CursorLockMode.Locked;
        Cursor.visible = false;
    }

    private void Update()
    {
        // switch styles
       //if (gameStatus.weaponEquipped == 1 && currentStyle != CameraStyle.Basic)
       //{
       //    SwitchCameraStyle(CameraStyle.Basic);
       //}
       //else if (gameStatus.weaponEquipped == 2 && currentStyle != CameraStyle.Shoot)
       //{
       //    SwitchCameraStyle(CameraStyle.Shoot);
       //}
        if (gameStatus.weaponEquipped == 1)
        {
            SwitchCameraStyle(CameraStyle.Basic);
        }
        else if (gameStatus.weaponEquipped == 2)
        {
            SwitchCameraStyle(CameraStyle.Shoot);
        }

        // rotate orientation
        Vector3 viewDir = player.position - new Vector3(transform.position.x, player.position.y, transform.position.z);
        orientation.forward = viewDir.normalized;

        // roate player object
        if(currentStyle == CameraStyle.Basic)
        {
            float horizontalInput = Input.GetAxis("Horizontal");
            float verticalInput = Input.GetAxis("Vertical");
            Vector3 inputDir = orientation.forward * verticalInput + orientation.right * horizontalInput;

            if (inputDir != Vector3.zero)
                playerObj.forward = Vector3.Slerp(playerObj.forward, inputDir.normalized, Time.deltaTime * rotationSpeed);
        }

        else if(currentStyle == CameraStyle.Shoot)
        {
            Vector3 dirToCombatLookAt = combatLookAt.position - new Vector3(transform.position.x, combatLookAt.position.y, transform.position.z);
            orientation.forward = dirToCombatLookAt.normalized;

            playerObj.forward = dirToCombatLookAt.normalized;
        }
    }

    private void SwitchCameraStyle(CameraStyle newStyle)
    {
        combatCam.SetActive(false);
        thirdPersonCam.SetActive(false);

        if (newStyle == CameraStyle.Basic) thirdPersonCam.SetActive(true);
        if (newStyle == CameraStyle.Shoot) combatCam.SetActive(true);

        currentStyle = newStyle;
    }
}
